import React from "react";
import '../App.css';

function Choicesection(){
  return (
    <div>
      <div className="itcompany"> 
        <h1><a href="#itcompany">Itcompany</a></h1>
      </div>
      <div className="lastchance"> 
        <a href="#lastchance">LastChance</a>
      </div>
      <div className="education"> 
        <a href="#education">education</a>
      </div>
    </div>
  )
}

export default Choicesection;